# Generated by Django 5.0.7 on 2024-09-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_status', models.CharField(choices=[('OSH', 'Ош'), ('KARA-SYY', 'Кара-Суу'), ('KURSHAB', 'Куршаб')], default='Ош', max_length=25, verbose_name='Город')),
                ('street', models.TextField(verbose_name='Улица')),
                ('home', models.TextField(verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Aдрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PRODUCTION', 'In Production'), ('DELIVERING', 'Left to Deliver'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='Submitted', max_length=25)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='carts.cart', verbose_name='заказ')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.flower')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
