# Generated by Django 5.0.7 on 2024-09-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='flowers.flower', verbose_name='отзыв'),
        ),
    ]
