# Generated by Django 5.0.7 on 2024-09-05 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0002_initial'),
        ('flowers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='отзыв'),
        ),
        migrations.AddField(
            model_name='feedbackmain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackmain', to=settings.AUTH_USER_MODEL, verbose_name='отзыв магазин'),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.flower'),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
