# Generated by Django 5.0.7 on 2024-09-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('COMPLETED', 'Завершено'), ('FAILED', 'Отклонено'), ('REFUNDED', 'Возращено')], default='В ожидании', max_length=20)),
                ('method', models.CharField(choices=[('CREDIT_CARD', 'Кредитной карточкой'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Банковский перевод'), ('Mbank', 'Мобильный перевод')], default='Mbank', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='оплата')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
